### ISSUE TITLE
missing stable_two_stage_multi_segmenter_clip_seg.py file in scripts

### ISSUE THREAD

**Issue by vjixy** [fudan-zvg/Semantic-Segment-Anything#1]
I cloned the repo and run this command
python scripts/stable_two_stage_multi_segmenter_clip_seg.py --data_dir=data/examples --out_dir=output --world_size=8 --save_img
i got:
python3: can't open file '/content/Semantic-Segment-Anything/scripts/stable_two_stage_multi_segmenter_clip_seg.py': [Errno 2] No such file or directory

**Comment by CJQ-CS-FD** [comment]
Thanks. I have updated the command in the README. Please use the following command: 
```bash
python scripts/main.py --data_dir=data/examples --out_dir=output --world_size=8 --save_img
```
