### ISSUE TITLE
About env

### ISSUE THREAD

**Issue by wongts44** [fudan-zvg/Semantic-Segment-Anything#11]
Great Job!!!
How about creating an environment without using Conda, such as using Python from virtualenv, and what libraries are needed?

**Comment by KleinYuan** [comment]
Using either anaconda or docker can make your life way easier.

In case you are interested in doing this in docker, I just wrapped up a dockerized version on top of this: https://github.com/KleinYuan/simple-semantic-segment-anything-annotator
