### ISSUE TITLE
是否能用于stable diffusion？

### ISSUE THREAD

**Issue by toniedeng** [fudan-zvg/Semantic-Segment-Anything#18]
如何与facebook的 segment anything 安装在一起？

**Comment by CJQ-CS-FD** [comment]
Regarding the possibility of using stable diffusion, the current version does not support it. To install SAM into the Conda environment, please refer to the "Installation" section in the README. Execute the following command.
```bash
# install segment-anything
cd ..
git clone git@github.com:facebookresearch/segment-anything.git
cd segment-anything; pip install -e .; cd ../Semantic-Segment-Anything
```
