### ISSUE TITLE
显存占用

### ISSUE THREAD

**Issue by houshuaipeng** [fudan-zvg/Semantic-Segment-Anything#19]
请问您在推理时使用的显卡显存是多少呢？我使用24G显存的4090推理时爆显存了，请问至少应该使用多少张以及多大显存的显卡呢？

**Comment by CJQ-CS-FD** [comment]
Hello, we have updated the code and you can pull the latest version. The small version of SSA-engine requires only 12GB of memory, while the base version takes 14GB. (The result is tested on SA-1B dataset) If you wish to use both SSA-engine and SAM together, you will need larger graphics memory. Please refer to the Memory Usage section in the Readme for more detailed information.

**Comment by houshuaipeng** [comment]
Thank you for your patient answer.
