### ISSUE TITLE
Get each segments from output of semantic segmentation

### ISSUE THREAD

**Issue by gjustin40** [fudan-zvg/Semantic-Segment-Anything#20]
Thank you for sharing a wonderful code!

I want to get segments of specific class from result.

Segmentation results have multiple classes, but I only want to see the segmentation results for a specific class. However, the resulting data (json) does not provide information on the coordinates of the segments or the index for each class, making it difficult to access the desired information.

I tried extracting unique the color of segments, but 'unique of color' and 'number of segments' are different....so it failed

for example, I just want mask that pixel's class_name is 'building'.

What can be done?
Thanks

**Comment by Jiaqi-Chen-00** [comment]
You can refer to this issue: https://github.com/fudan-zvg/Semantic-Segment-Anything/issues/35
