### ISSUE TITLE
Run without GPU

### ISSUE THREAD

**Issue by AnnaBhlr** [fudan-zvg/Semantic-Segment-Anything#23]
Hi,
thanks for the amazing code! Is there any chance to get it running without a cuda capable gpu? Maybe via cpu (as for the sam)?
Thanks!

**Comment by houshuaipeng** [comment]
I have the same question.

**Comment by houshuaipeng** [comment]
I've got the solution, for example with main_ssa_engine.py:
1、comment out the first line in main(): dist.init_process_group("nccl", rank=rank, world_size=args.world_size)
2、change the last 4 line :
`    if args.world_size > 1:
        mp.spawn(main,args=(args,),nprocs=args.world_size,join=True)
    else:
        main(0, args)`
into one line:
`main('cpu', args)`

**Comment by ibrandiay** [comment]
@houshuaipeng Your solution does not work, the first argument of the hand must be an integer and not a string as you advise us.

**Comment by AnnaBhlr** [comment]
@ibrandiay  It works if you change rank in l99 to 0 resulting in:
```
local_filenames = filenames[(len(filenames) // args.world_size + 1) * 0 : (len(filenames) // args.world_size + 1) * (0 + 1)]
```

**Comment by ibrandiay** [comment]
Thank @AnnaBhlr it work well now !!
