### ISSUE TITLE
How to create image mask from JSON

### ISSUE THREAD

**Issue by Ragunath-planetre** [fudan-zvg/Semantic-Segment-Anything#27]
Hi Team,

Am so much interested in semantic segment. is there any way to create image mask for each segment using the JSON output.

https://replicate.delivery/pbxt/ZNh6er6mvwWfNUSZWdfStS9lTfQl1PnCGkk6QI9zvJWm8XGDB/seg_out.json

**Comment by Jiaqi-Chen-00** [comment]
You can refer to the following code to visualize the mask: https://github.com/fudan-zvg/Semantic-Segment-Anything/blob/main/scripts/pipeline.py#L126-L135
