### ISSUE TITLE
Simple Python code available?

### ISSUE THREAD

**Issue by Marcophono2** [fudan-zvg/Semantic-Segment-Anything#29]
Hello!
I love this project and the impressing results! But I would like to handle it simple with a few lines of Python code. Is there anything available? I tried to filter out the relevant parts of your project scripts but failed.
Simple giving the address to a single image and in return receiving an array or a list with labels, coordinates etc. Is that possible?

Best regards
Marc

**Comment by Jiaqi-Chen-00** [comment]
You can simply follow the instructions in the readme to run the script. However, if you filter out the relevant parts of your project scripts, we cannot guarantee that the code will still function properly.
