### ISSUE TITLE
推理耗时非常慢

### ISSUE THREAD

**Issue by CVRS-CJH** [fudan-zvg/Semantic-Segment-Anything#34]
我使用main_ssa.py进行单张图像推理，硬件为单个A100显卡，40G显存，发现在Semantic Voting模块耗时很多，每个mask都几乎需要处理1s，和git中有出入，请问这是正常的吗

**Comment by Jiaqi-Chen-00** [comment]
Excluding the inference time of SAM, the speed for SSA on the SA-1B dataset is approximately 0.5-4 seconds per image (varying depending on image size). We suggest checking if your SSA computations are happening on the GPU and verifying if other parameters align with those in the repository.

**Comment by Yonglild** [comment]
@CVRS-CJH  @Jiaqi-Chen-00 我也是单张图推理（Tesla T4, 16g）, 整个过程大约要50s左右。其中SAM的时间大概要49s！！
请问README中的1.149s是包含了SAM的推理时间吗？
