### ISSUE TITLE
Release model weights

### ISSUE THREAD

**Issue by simi-asher** [fudan-zvg/Semantic-Segment-Anything#5]
Hi 

Really appreciate this work. Do you plan on releasing model weights/checkpoints for SSA? Would really appreciate it.

Thanks

**Comment by ericflo** [comment]
Looks like this repo uses a suite of pre-trained models, but it doesn't need its own weights. Maybe I'm missing something, but I think you should have what you need.

**Comment by lzrobots** [comment]
You just need to run the commands provided in the **Quick start** section, and the checkpoint will be downloaded automatically.
