### ISSUE TITLE
Repository license needed

### ISSUE THREAD

**Issue by thompsonmj** [fudan-zvg/Semantic-Segment-Anything#9]
This work looks quite valuable! I would like to explore SSA, but I noticed there is no license.

Would you please add a license that helps clarify the terms under which this work can or cannot be used, edited, extended, and/or redistributed?

**Comment by lzrobots** [comment]
Thanks! We have added the Apache 2.0 license.

**Comment by vectris-dev** [comment]
This work is great, the license page says Apache however there is also `Copyright 2023 Zhang Vision Group, Fudan University. All rights reserved.` Under the Apache license commercial use is permitted, is that the case here?
